import { SeasonMenu } from "../../SeasonMenu";
import FrontCover from '../../../vetores/Capa/breaking-bad-capa.jpg'
import { Episode } from "../../Episodes";

export function BreakingBadTemp() {
    return (
        <aside className="flex">
            <div className="flex flex-col gap-3 duration-500">
                <SeasonMenu
                    title="1° Temporada"
                    trueOrFalse={false}
                    episode1={<Episode
                        title="Breaking Bad"
                        slug="breaking-bad-S1E1"
                        slugOne="series"
                        subTitle="Season 1 Episode 1"
                        picture={FrontCover}
                        focusBg="bg-gray-500"
                        focusTitleColor="text-gray-200"
                    />}
                    episode2={<Episode
                        title="Breaking Bad"
                        slug="breaking-bad-S1E2"
                        slugOne="series"
                        subTitle="Season 1 Episode 2"
                        picture={FrontCover}
                        focusBg="bg-gray-500"
                        focusTitleColor="text-gray-200" />}
                    episode3={<Episode
                        title="Breaking Bad"
                        slug="breaking-bad-S1E3"
                        slugOne="series"
                        subTitle="Season 1 Episode 3"
                        picture={FrontCover}
                        focusBg="bg-gray-500"
                        focusTitleColor="text-gray-200" />}
                    episode4={<Episode
                        title="Breaking Bad"
                        slug="breaking-bad-S1E4"
                        slugOne="series"
                        subTitle="Season 1 Episode 4"
                        picture={FrontCover}
                        focusBg="bg-gray-500"
                        focusTitleColor="text-gray-200" />}
                    episode5={<Episode
                        title="Breaking Bad"
                        slug="breaking-bad-S1E5"
                        slugOne="series"
                        subTitle="Season 1 Episode 5"
                        picture={FrontCover}
                        focusBg="bg-gray-500"
                        focusTitleColor="text-gray-200" />}
                    episode6={<Episode
                        title="Breaking Bad"
                        slug="breaking-bad-S1E6"
                        slugOne="series"
                        subTitle="Season 1 Episode 6"
                        picture={FrontCover}
                        focusBg="bg-gray-500"
                        focusTitleColor="text-gray-200" />}
                    episode7={<Episode
                        title="Breaking Bad"
                        slug="breaking-bad-S1E7"
                        slugOne="series"
                        subTitle="Season 1 Episode 7"
                        picture={FrontCover}
                        focusBg="bg-gray-500"
                        focusTitleColor="text-gray-200" />}
                    episode8=''
                    episode9=""
                    episode10=""
                />
                <SeasonMenu
                    title="2° Temporada"
                    trueOrFalse={false}
                    episode1={<Episode
                        title="Breaking Bad"
                        slug="breaking-bad-S2E1"
                        slugOne="series"
                        subTitle="Season 2 Episode 1"
                        picture={FrontCover}
                        focusBg="bg-gray-500"
                        focusTitleColor="text-gray-200" />}
                    episode2={<Episode
                        title="Breaking Bad"
                        slug="breaking-bad-S2E2"
                        slugOne="series"
                        subTitle="Season 2 Episode 2"
                        picture={FrontCover}
                        focusBg="bg-gray-500"
                        focusTitleColor="text-gray-200" />}
                    episode3={<Episode
                        title="Breaking Bad"
                        slug="breaking-bad-S2E3"
                        slugOne="series"
                        subTitle="Season 2 Episode 3"
                        picture={FrontCover}
                        focusBg="bg-gray-500"
                        focusTitleColor="text-gray-200" />}
                    episode4={<Episode
                        title="Breaking Bad"
                        slug="breaking-bad-S2E4"
                        slugOne="series"
                        subTitle="Season 2 Episode 4"
                        picture={FrontCover}
                        focusBg="bg-gray-500"
                        focusTitleColor="text-gray-200" />}
                    episode5={<Episode
                        title="Breaking Bad"
                        slug="breaking-bad-S2E5"
                        slugOne="series"
                        subTitle="Season 2 Episode 5"
                        picture={FrontCover}
                        focusBg="bg-gray-500"
                        focusTitleColor="text-gray-200" />}
                    episode6={<Episode
                        title="Breaking Bad"
                        slug="breaking-bad-S2E6"
                        slugOne="series"
                        subTitle="Season 2 Episode 6"
                        picture={FrontCover}
                        focusBg="bg-gray-500"
                        focusTitleColor="text-gray-200" />}
                    episode7={<Episode
                        title="Breaking Bad"
                        slug="breaking-bad-S2E7"
                        slugOne="series"
                        subTitle="Season 2 Episode 7"
                        picture={FrontCover}
                        focusBg="bg-gray-500"
                        focusTitleColor="text-gray-200" />}
                    episode8={<Episode
                        title="Breaking Bad"
                        slug="breaking-bad-S2E8"
                        slugOne="series"
                        subTitle="Season 2 Episode 8"
                        picture={FrontCover}
                        focusBg="bg-gray-500"
                        focusTitleColor="text-gray-200" />}
                    episode9={<Episode
                        title="Breaking Bad"
                        slug="breaking-bad-S2E9"
                        slugOne="series"
                        subTitle="Season 2 Episode 9"
                        picture={FrontCover}
                        focusBg="bg-gray-500"
                        focusTitleColor="text-gray-200" />}
                    episode10={<Episode
                        title="Breaking Bad"
                        slug="breaking-bad-S2E10"
                        slugOne="series"
                        subTitle="Season 2 Episode 10"
                        picture={FrontCover}
                        focusBg="bg-gray-500"
                        focusTitleColor="text-gray-200" />}
                />
                <SeasonMenu
                    title="3° Temporada"
                    trueOrFalse={false}
                    episode1={<Episode
                        title="Breaking Bad"
                        slug="breaking-bad-S3E1"
                        slugOne="series"
                        subTitle="Season 3 Episode 1"
                        picture={FrontCover}
                        focusBg="bg-gray-500"
                        focusTitleColor="text-gray-200" />}
                    episode2={<Episode
                        title="Breaking Bad"
                        slug="breaking-bad-S3E2"
                        slugOne="series"
                        subTitle="Season 3 Episode 2"
                        picture={FrontCover}
                        focusBg="bg-gray-500"
                        focusTitleColor="text-gray-200" />}
                    episode3={<Episode
                        title="Breaking Bad"
                        slug="breaking-bad-S3E3"
                        slugOne="series"
                        subTitle="Season 3 Episode 3"
                        picture={FrontCover}
                        focusBg="bg-gray-500"
                        focusTitleColor="text-gray-200" />}
                    episode4={<Episode
                        title="Breaking Bad"
                        slug="breaking-bad-S3E4"
                        slugOne="series"
                        subTitle="Season 3 Episode 4"
                        picture={FrontCover}
                        focusBg="bg-gray-500"
                        focusTitleColor="text-gray-200" />}
                    episode5={<Episode
                        title="Breaking Bad"
                        slug="breaking-bad-S3E5"
                        slugOne="series"
                        subTitle="Season 3 Episode 5"
                        picture={FrontCover}
                        focusBg="bg-gray-500"
                        focusTitleColor="text-gray-200" />}
                    episode6={<Episode
                        title="Breaking Bad"
                        slug="breaking-bad-S3E6"
                        slugOne="series"
                        subTitle="Season 3 Episode 6"
                        picture={FrontCover}
                        focusBg="bg-gray-500"
                        focusTitleColor="text-gray-200" />}
                    episode7={<Episode
                        title="Breaking Bad"
                        slug="breaking-bad-S3E7"
                        slugOne="series"
                        subTitle="Season 3 Episode 7"
                        picture={FrontCover}
                        focusBg="bg-gray-500"
                        focusTitleColor="text-gray-200" />}
                    episode8={<Episode
                        title="Breaking Bad"
                        slug="breaking-bad-S3E8"
                        slugOne="series"
                        subTitle="Season 3 Episode 8"
                        picture={FrontCover}
                        focusBg="bg-gray-500"
                        focusTitleColor="text-gray-200" />}
                    episode9={<Episode
                        title="Breaking Bad"
                        slug="breaking-bad-S3E9"
                        slugOne="series"
                        subTitle="Season 3 Episode 9"
                        picture={FrontCover}
                        focusBg="bg-gray-500"
                        focusTitleColor="text-gray-200" />}
                    episode10={<Episode
                        title="Breaking Bad"
                        slug="breaking-bad-S3E10"
                        slugOne="series"
                        subTitle="Season 3 Episode 10"
                        picture={FrontCover}
                        focusBg="bg-gray-500"
                        focusTitleColor="text-gray-200" />}
                />
                <SeasonMenu
                    title="4° Temporada"
                    trueOrFalse={false}
                    episode1={<Episode
                        title="Breaking Bad"
                        slug="breaking-bad-S4E1"
                        slugOne="series"
                        subTitle="Season 4 Episode 1"
                        picture={FrontCover}
                        focusBg="bg-gray-500"
                        focusTitleColor="text-gray-200" />}
                    episode2={<Episode
                        title="Breaking Bad"
                        slug="breaking-bad-S4E2"
                        slugOne="series"
                        subTitle="Season 4 Episode 2"
                        picture={FrontCover}
                        focusBg="bg-gray-500"
                        focusTitleColor="text-gray-200" />}
                    episode3={<Episode
                        title="Breaking Bad"
                        slug="breaking-bad-S4E3"
                        slugOne="series"
                        subTitle="Season 4 Episode 3"
                        picture={FrontCover}
                        focusBg="bg-gray-500"
                        focusTitleColor="text-gray-200" />}
                    episode4={<Episode
                        title="Breaking Bad"
                        slug="breaking-bad-S4E4"
                        slugOne="series"
                        subTitle="Season 4 Episode 4"
                        picture={FrontCover}
                        focusBg="bg-gray-500"
                        focusTitleColor="text-gray-200" />}
                    episode5={<Episode
                        title="Breaking Bad"
                        slug="breaking-bad-S4E5"
                        slugOne="series"
                        subTitle="Season 4 Episode 5"
                        picture={FrontCover}
                        focusBg="bg-gray-500"
                        focusTitleColor="text-gray-200" />}
                    episode6={<Episode
                        title="Breaking Bad"
                        slug="breaking-bad-S4E6"
                        slugOne="series"
                        subTitle="Season 4 Episode 6"
                        picture={FrontCover}
                        focusBg="bg-gray-500"
                        focusTitleColor="text-gray-200" />}
                    episode7={<Episode
                        title="Breaking Bad"
                        slug="breaking-bad-S4E7"
                        slugOne="series"
                        subTitle="Season 4 Episode 7"
                        picture={FrontCover}
                        focusBg="bg-gray-500"
                        focusTitleColor="text-gray-200" />}
                    episode8={<Episode
                        title="Breaking Bad"
                        slug="breaking-bad-S4E8"
                        slugOne="series"
                        subTitle="Season 4 Episode 8"
                        picture={FrontCover}
                        focusBg="bg-gray-500"
                        focusTitleColor="text-gray-200" />}
                    episode9={<Episode
                        title="Breaking Bad"
                        slug="breaking-bad-S4E9"
                        slugOne="series"
                        subTitle="Season 4 Episode 9"
                        picture={FrontCover}
                        focusBg="bg-gray-500"
                        focusTitleColor="text-gray-200" />}
                    episode10={<Episode
                        title="Breaking Bad"
                        slug="breaking-bad-S4E10"
                        slugOne="series"
                        subTitle="Season 4 Episode 10"
                        picture={FrontCover}
                        focusBg="bg-gray-500"
                        focusTitleColor="text-gray-200" />}
                />
                <SeasonMenu
                    title="5° Temporada"
                    trueOrFalse={false}
                    episode1={<Episode
                        title="Breaking Bad"
                        slug="breaking-bad-S5E1"
                        slugOne="series"
                        subTitle="Season 5 Episode 1"
                        picture={FrontCover}
                        focusBg="bg-gray-500"
                        focusTitleColor="text-gray-200" />}
                    episode2={<Episode
                        title="Breaking Bad"
                        slug="breaking-bad-S5E2"
                        slugOne="series"
                        subTitle="Season 5 Episode 2"
                        picture={FrontCover}
                        focusBg="bg-gray-500"
                        focusTitleColor="text-gray-200" />}
                    episode3={<Episode
                        title="Breaking Bad"
                        slug="breaking-bad-S5E3"
                        slugOne="series"
                        subTitle="Season 5 Episode 3"
                        picture={FrontCover}
                        focusBg="bg-gray-500"
                        focusTitleColor="text-gray-200" />}
                    episode4={<Episode
                        title="Breaking Bad"
                        slug="breaking-bad-S5E4"
                        slugOne="series"
                        subTitle="Season 5 Episode 4"
                        picture={FrontCover}
                        focusBg="bg-gray-500"
                        focusTitleColor="text-gray-200" />}
                    episode5={<Episode
                        title="Breaking Bad"
                        slug="breaking-bad-S5E5"
                        slugOne="series"
                        subTitle="Season 5 Episode 5"
                        picture={FrontCover}
                        focusBg="bg-gray-500"
                        focusTitleColor="text-gray-200" />}
                    episode6={<Episode
                        title="Breaking Bad"
                        slug="breaking-bad-S5E6"
                        slugOne="series"
                        subTitle="Season 5 Episode 6"
                        picture={FrontCover}
                        focusBg="bg-gray-500"
                        focusTitleColor="text-gray-200" />}
                    episode7={<Episode
                        title="Breaking Bad"
                        slug="breaking-bad-S5E7"
                        slugOne="series"
                        subTitle="Season 5 Episode 7"
                        picture={FrontCover}
                        focusBg="bg-gray-500"
                        focusTitleColor="text-gray-200" />}
                    episode8={<Episode
                        title="Breaking Bad"
                        slug="breaking-bad-S5E8"
                        slugOne="series"
                        subTitle="Season 5 Episode 8"
                        picture={FrontCover}
                        focusBg="bg-gray-500"
                        focusTitleColor="text-gray-200" />}
                    episode9=''
                    episode10=''
                />
            </div>
        </aside>
    )
}