import { SeasonMenu } from "../../SeasonMenu";
import FrontCover from '../../../vetores/Capa/the-boys-capa.jpg'
import { Episode } from "../../Episodes";

export function TemporadasTheBoys() {
    return (
        <aside className="flex">
            <div className="flex flex-col duration-500 gap-3">
                <SeasonMenu
                    title="1° Temporada"
                    trueOrFalse={false}
                    episode1={<Episode
                        title="The Boys"
                        slug="the-boys-S1E1"
                        slugOne="series"
                        subTitle="Season 1 Episode 1"
                        picture={FrontCover}
                        focusBg="bg-gray-500"
                        focusTitleColor="text-gray-200" />}
                    episode2={<Episode
                        title="The Boys"
                        slug="the-boys-S1E2"
                        slugOne="series"
                        subTitle="Season 1 Episode 2"
                        picture={FrontCover}
                        focusBg="bg-gray-500"
                        focusTitleColor="text-gray-200" />}
                    episode3={<Episode
                        title="The Boys"
                        slug="the-boys-S1E3"
                        slugOne="series"
                        subTitle="Season 1 Episode 3"
                        picture={FrontCover}
                        focusBg="bg-gray-500"
                        focusTitleColor="text-gray-200" />}
                    episode4={<Episode
                        title="The Boys"
                        slug="the-boys-S1E4"
                        slugOne="series"
                        subTitle="Season 1 Episode 4"
                        picture={FrontCover}
                        focusBg="bg-gray-500"
                        focusTitleColor="text-gray-200" />}
                    episode5={<Episode
                        title="The Boys"
                        slug="the-boys-S1E5"
                        slugOne="series"
                        subTitle="Season 1 Episode 5"
                        picture={FrontCover}
                        focusBg="bg-gray-500"
                        focusTitleColor="text-gray-200" />}
                    episode6={<Episode
                        title="The Boys"
                        slug="the-boys-S1E6"
                        slugOne="series"
                        subTitle="Season 1 Episode 6"
                        picture={FrontCover}
                        focusBg="bg-gray-500"
                        focusTitleColor="text-gray-200" />}
                    episode7={<Episode
                        title="The Boys"
                        slug="the-boys-S1E7"
                        slugOne="series"
                        subTitle="Season 1 Episode 7"
                        picture={FrontCover}
                        focusBg="bg-gray-500"
                        focusTitleColor="text-gray-200" />}
                    episode8={<Episode
                        title="The Boys"
                        slug="the-boys-S1E8"
                        slugOne="series"
                        subTitle="Season 1 Episode 8"
                        picture={FrontCover}
                        focusBg="bg-gray-500"
                        focusTitleColor="text-gray-200" />}
                    episode9=""
                    episode10=""
                />
                <SeasonMenu
                    title="2° Temporada"
                    trueOrFalse={false}
                    episode1={<Episode
                        title="The Boys"
                        slug="the-boys-S2E1"
                        slugOne="series"
                        subTitle="Season 2 Episode 1"
                        picture={FrontCover}
                        focusBg="bg-gray-500"
                        focusTitleColor="text-gray-200" />}
                    episode2={<Episode
                        title="The Boys"
                        slug="the-boys-S2E2"
                        slugOne="series"
                        subTitle="Season 2 Episode 2"
                        picture={FrontCover}
                        focusBg="bg-gray-500"
                        focusTitleColor="text-gray-200" />}
                    episode3={<Episode
                        title="The Boys"
                        slug="the-boys-S2E3"
                        slugOne="series"
                        subTitle="Season 2 Episode 3"
                        picture={FrontCover}
                        focusBg="bg-gray-500"
                        focusTitleColor="text-gray-200" />}
                    episode4={<Episode
                        title="The Boys"
                        slug="the-boys-S2E4"
                        slugOne="series"
                        subTitle="Season 2 Episode 4"
                        picture={FrontCover}
                        focusBg="bg-gray-500"
                        focusTitleColor="text-gray-200" />}
                    episode5={<Episode
                        title="The Boys"
                        slug="the-boys-S2E5"
                        slugOne="series"
                        subTitle="Season 2 Episode 5"
                        picture={FrontCover}
                        focusBg="bg-gray-500"
                        focusTitleColor="text-gray-200" />}
                    episode6={<Episode
                        title="The Boys"
                        slug="the-boys-S2E6"
                        slugOne="series"
                        subTitle="Season 2 Episode 6"
                        picture={FrontCover}
                        focusBg="bg-gray-500"
                        focusTitleColor="text-gray-200" />}
                    episode7={<Episode
                        title="The Boys"
                        slug="the-boys-S2E7"
                        slugOne="series"
                        subTitle="Season 2 Episode 7"
                        picture={FrontCover}
                        focusBg="bg-gray-500"
                        focusTitleColor="text-gray-200" />}
                    episode8={<Episode
                        title="The Boys"
                        slug="the-boys-S2E8"
                        slugOne="series"
                        subTitle="Season 2 Episode 8"
                        picture={FrontCover}
                        focusBg="bg-gray-500"
                        focusTitleColor="text-gray-200" />}
                    episode9=''
                    episode10=''
                />
                <SeasonMenu
                    title="3° Temporada"
                    trueOrFalse={false}
                    episode1={<Episode
                        title="The Boys"
                        slug="the-boys-S3E1"
                        slugOne="series"
                        subTitle="Season 3 Episode 1"
                        picture={FrontCover}
                        focusBg="bg-gray-500"
                        focusTitleColor="text-gray-200" />}
                    episode2={<Episode
                        title="The Boys"
                        slug="the-boys-S3E2"
                        slugOne="series"
                        subTitle="Season 3 Episode 2"
                        picture={FrontCover}
                        focusBg="bg-gray-500"
                        focusTitleColor="text-gray-200" />}
                    episode3={<Episode
                        title="The Boys"
                        slug="the-boys-S3E3"
                        slugOne="series"
                        subTitle="Season 3 Episode 3"
                        picture={FrontCover}
                        focusBg="bg-gray-500"
                        focusTitleColor="text-gray-200" />}
                    episode4={<Episode
                        title="The Boys"
                        slug="the-boys-S3E4"
                        slugOne="series"
                        subTitle="Season 3 Episode 4"
                        picture={FrontCover}
                        focusBg="bg-gray-500"
                        focusTitleColor="text-gray-200" />}
                    episode5={<Episode
                        title="The Boys"
                        slug="the-boys-S3E5"
                        slugOne="series"
                        subTitle="Season 3 Episode 5"
                        picture={FrontCover}
                        focusBg="bg-gray-500"
                        focusTitleColor="text-gray-200" />}
                    episode6={<Episode
                        title="The Boys"
                        slug="the-boys-S3E6"
                        slugOne="series"
                        subTitle="Season 3 Episode 6"
                        picture={FrontCover}
                        focusBg="bg-gray-500"
                        focusTitleColor="text-gray-200" />}
                    episode7={<Episode
                        title="The Boys"
                        slug="the-boys-S3E7"
                        slugOne="series"
                        subTitle="Season 3 Episode 7"
                        picture={FrontCover}
                        focusBg="bg-gray-500"
                        focusTitleColor="text-gray-200" />}
                    episode8={<Episode
                        title="The Boys"
                        slug="the-boys-S3E8"
                        slugOne="series"
                        subTitle="Season 3 Episode 8"
                        picture={FrontCover}
                        focusBg="bg-gray-500"
                        focusTitleColor="text-gray-200" />}
                    episode9=''
                    episode10=''
                />
            </div>
        </aside>
    )
}