
import { Header } from "../components/Header";
import { useParams } from 'react-router-dom';

import { PlayerGotS1E1 } from "../components/Players/got/S1/PlayerGot-S1E1";
import { PlayerGotS1E2 } from "../components/Players/got/S1/PlayerGot-S1E2";
import { PlayerGotS1E3 } from "../components/Players/got/S1/PlayerGot-S1E3";
import { PlayerGotS1E4 } from "../components/Players/got/S1/PlayerGot-S1E4";
import { PlayerGotS1E5 } from "../components/Players/got/S1/PlayerGot-S1E5";
import { PlayerGotS1E6 } from "../components/Players/got/S1/PlayerGot-S1E6";
import { PlayerGotS1E7 } from "../components/Players/got/S1/PlayerGot-S1E7";
import { PlayerGotS1E8 } from "../components/Players/got/S1/PlayerGot-S1E8";
import { PlayerGotS1E9 } from "../components/Players/got/S1/PlayerGot-S1E9";
import { PlayerGotS1E10 } from "../components/Players/got/S1/PlayerGot-S1E10";
import { PlayerGotS2E1 } from "../components/Players/got/S2/PlayerGot-S2E1";
import { PlayerGotS2E2 } from "../components/Players/got/S2/PlayerGot-S2E2";
import { PlayerGotS2E3 } from "../components/Players/got/S2/PlayerGot-S2E3";
import { PlayerGotS2E5 } from "../components/Players/got/S2/PlayerGot-S2E5";
import { PlayerGotS2E4 } from "../components/Players/got/S2/PlayerGot-S2E4";
import { PlayerGotS2E6 } from "../components/Players/got/S2/PlayerGot-S2E6";
import { PlayerGotS2E7 } from "../components/Players/got/S2/PlayerGot-S2E7";
import { PlayerGotS2E8 } from "../components/Players/got/S2/PlayerGot-S2E8";
import { PlayerGotS2E9 } from "../components/Players/got/S2/PlayerGot-S2E9";
import { PlayerGotS2E10 } from "../components/Players/got/S2/PlayerGot-S2E10";
import { PlayerGotS3E1 } from "../components/Players/got/S3/PlayerGot-S3E1";
import { PlayerGotS3E2 } from "../components/Players/got/S3/PlayerGot-S3E2";
import { PlayerGotS3E3 } from "../components/Players/got/S3/PlayerGot-S3E3";
import { PlayerGotS3E4 } from "../components/Players/got/S3/PlayerGot-S3E4";
import { PlayerGotS3E5 } from "../components/Players/got/S3/PlayerGot-S3E5";
import { PlayerGotS3E6 } from "../components/Players/got/S3/PlayerGot-S3E6";
import { PlayerGotS3E7 } from "../components/Players/got/S3/PlayerGot-S3E7";
import { PlayerGotS3E8 } from "../components/Players/got/S3/PlayerGot-S3E8";
import { PlayerGotS3E9 } from "../components/Players/got/S3/PlayerGot-S3E9";
import { PlayerGotS3E10 } from "../components/Players/got/S3/PlayerGot-S3E10";
import { PlayerGotS4E1 } from "../components/Players/got/S4/PlayerGot-S4E1";
import { PlayerGotS4E2 } from "../components/Players/got/S4/PlayerGot-S4E2";
import { PlayerGotS4E3 } from "../components/Players/got/S4/PlayerGot-S4E3";
import { PlayerGotS4E4 } from "../components/Players/got/S4/PlayerGot-S4E4";
import { PlayerGotS4E5 } from "../components/Players/got/S4/PlayerGot-S4E5";
import { PlayerGotS4E6 } from "../components/Players/got/S4/PlayerGot-S4E6";
import { PlayerGotS4E7 } from "../components/Players/got/S4/PlayerGot-S4E7";
import { PlayerGotS4E8 } from "../components/Players/got/S4/PlayerGot-S4E8";
import { PlayerGotS4E9 } from "../components/Players/got/S4/PlayerGot-S4E9";
import { PlayerGotS4E10 } from "../components/Players/got/S4/PlayerGot-S4E10";
import { PlayerGotS5E1 } from "../components/Players/got/S5/PlayerGot-S5E1";
import { PlayerGotS5E2 } from "../components/Players/got/S5/PlayerGot-S5E2";
import { PlayerGotS5E3 } from "../components/Players/got/S5/PlayerGot-S5E3";
import { PlayerGotS5E4 } from "../components/Players/got/S5/PlayerGot-S5E4";
import { PlayerGotS5E5 } from "../components/Players/got/S5/PlayerGot-S5E5";
import { PlayerGotS5E6 } from "../components/Players/got/S5/PlayerGot-S5E6";
import { PlayerGotS5E7 } from "../components/Players/got/S5/PlayerGot-S5E7";
import { PlayerGotS5E8 } from "../components/Players/got/S5/PlayerGot-S5E8";
import { PlayerGotS5E9 } from "../components/Players/got/S5/PlayerGot-S5E9";
import { PlayerGotS5E10 } from "../components/Players/got/S5/PlayerGot-S5E10";
import { PlayerGotHome } from "../components/Players/got/S1/PlayerHome";
import { PlayerBreakingBadS1E1 } from "../components/Players/breaking-bad/S1/PlayerBreakingBad-S1E1";
import { PlayerBreakingBadS1E2 } from "../components/Players/breaking-bad/S1/PlayerBreakingBad-S1E2";
import { PlayerBreakingBadS1E3 } from "../components/Players/breaking-bad/S1/PlayerBreakingBad-S1E3";
import { PlayerBreakingBadS1E4 } from "../components/Players/breaking-bad/S1/PlayerBreakingBad-S1E4";
import { PlayerBreakingBadS1E5 } from "../components/Players/breaking-bad/S1/PlayerBreakingBad-S1E5";
import { PlayerBreakingBadS1E6 } from "../components/Players/breaking-bad/S1/PlayerBreakingBad-S1E6";
import { PlayerBreakingBadS1E7 } from "../components/Players/breaking-bad/S1/PlayerBreakingBad-S1E7";
import { PlayerBreakingBadS2E1 } from "../components/Players/breaking-bad/S2/PlayerBreakingBad-S2E1";
import { PlayerBreakingBadS2E2 } from "../components/Players/breaking-bad/S2/PlayerBreakingBad-S2E2";
import { PlayerBreakingBadS2E3 } from "../components/Players/breaking-bad/S2/PlayerBreakingBad-S2E3";
import { PlayerBreakingBadS2E4 } from "../components/Players/breaking-bad/S2/PlayerBreakingBad-S2E4";
import { PlayerBreakingBadS2E5 } from "../components/Players/breaking-bad/S2/PlayerBreakingBad-S2E5";
import { PlayerBreakingBadS2E6 } from "../components/Players/breaking-bad/S2/PlayerBreakingBad-S2E6";
import { PlayerBreakingBadS2E7 } from "../components/Players/breaking-bad/S2/PlayerBreakingBad-S2E7";
import { PlayerBreakingBadS2E8 } from "../components/Players/breaking-bad/S2/PlayerBreakingBad-S2E8";
import { PlayerBreakingBadS2E9 } from "../components/Players/breaking-bad/S2/PlayerBreakingBad-S2E9";
import { PlayerBreakingBadS2E10 } from "../components/Players/breaking-bad/S2/PlayerBreakingBad-S2E10";
import { PlayerBreakingBadS3E1 } from "../components/Players/breaking-bad/S3/PlayerBreakingBad-S3E1";
import { PlayerBreakingBadS3E10 } from "../components/Players/breaking-bad/S3/PlayerBreakingBad-S3E10";
import { PlayerBreakingBadS3E9 } from "../components/Players/breaking-bad/S3/PlayerBreakingBad-S3E9";
import { PlayerBreakingBadS3E8 } from "../components/Players/breaking-bad/S3/PlayerBreakingBad-S3E8";
import { PlayerBreakingBadS3E7 } from "../components/Players/breaking-bad/S3/PlayerBreakingBad-S3E7";
import { PlayerBreakingBadS3E6 } from "../components/Players/breaking-bad/S3/PlayerBreakingBad-S3E6";
import { PlayerBreakingBadS3E5 } from "../components/Players/breaking-bad/S3/PlayerBreakingBad-S3E5";
import { PlayerBreakingBadS3E4 } from "../components/Players/breaking-bad/S3/PlayerBreakingBad-S3E4";
import { PlayerBreakingBadS3E3 } from "../components/Players/breaking-bad/S3/PlayerBreakingBad-S3E3";
import { PlayerBreakingBadS3E2 } from "../components/Players/breaking-bad/S3/PlayerBreakingBad-S3E2";
import { PlayerBreakingBadS4E1 } from "../components/Players/breaking-bad/S4/PlayerBreakingBad-S4E1";
import { PlayerBreakingBadS4E2 } from "../components/Players/breaking-bad/S4/PlayerBreakingBad-S4E2";
import { PlayerBreakingBadS4E3 } from "../components/Players/breaking-bad/S4/PlayerBreakingBad-S4E3";
import { PlayerBreakingBadS4E4 } from "../components/Players/breaking-bad/S4/PlayerBreakingBad-S4E4";
import { PlayerBreakingBadS4E5 } from "../components/Players/breaking-bad/S4/PlayerBreakingBad-S4E5";
import { PlayerBreakingBadS4E6 } from "../components/Players/breaking-bad/S4/PlayerBreakingBad-S4E6";
import { PlayerBreakingBadS4E7 } from "../components/Players/breaking-bad/S4/PlayerBreakingBad-S4E7";
import { PlayerBreakingBadS4E8 } from "../components/Players/breaking-bad/S4/PlayerBreakingBad-S4E8";
import { PlayerBreakingBadS4E9 } from "../components/Players/breaking-bad/S4/PlayerBreakingBad-S4E9";
import { PlayerBreakingBadS4E10 } from "../components/Players/breaking-bad/S4/PlayerBreakingBad-S4E10";
import { PlayerBreakingBadS5E8 } from "../components/Players/breaking-bad/S5/PlayerBreakingBad-S5E8";
import { PlayerBreakingBadS5E7 } from "../components/Players/breaking-bad/S5/PlayerBreakingBad-S5E7";
import { PlayerBreakingBadS5E6 } from "../components/Players/breaking-bad/S5/PlayerBreakingBad-S5E6";
import { PlayerBreakingBadS5E5 } from "../components/Players/breaking-bad/S5/PlayerBreakingBad-S5E5";
import { PlayerBreakingBadS5E4 } from "../components/Players/breaking-bad/S5/PlayerBreakingBad-S5E4";
import { PlayerBreakingBadS5E3 } from "../components/Players/breaking-bad/S5/PlayerBreakingBad-S5E3";
import { PlayerBreakingBadS5E2 } from "../components/Players/breaking-bad/S5/PlayerBreakingBad-S5E2";
import { PlayerBreakingBadS5E1 } from "../components/Players/breaking-bad/S5/PlayerBreakingBad-S5E1";
import { PlayerBreakingBadHome } from "../components/Players/breaking-bad/S1/BreakingBadPlayer-Home";
import { PlayerTheBoysHome } from "../components/Players/the-boys/S1/PlayerTheBoysHome";
import { PlayerTheBoysS1E1 } from "../components/Players/the-boys/S1/PlayerThe Boys-S1E1";
import { PlayerTheBoysS1E8 } from "../components/Players/the-boys/S1/PlayerThe Boys-S1E8";
import { PlayerTheBoysS1E7 } from "../components/Players/the-boys/S1/PlayerThe Boys-S1E7";
import { PlayerTheBoysS1E6 } from "../components/Players/the-boys/S1/PlayerThe Boys-S1E6";
import { PlayerTheBoysS1E5 } from "../components/Players/the-boys/S1/PlayerThe Boys-S1E5";
import { PlayerTheBoysS1E4 } from "../components/Players/the-boys/S1/PlayerThe Boys-S1E4";
import { PlayerTheBoysS1E3 } from "../components/Players/the-boys/S1/PlayerThe Boys-S1E3";
import { PlayerTheBoysS1E2 } from "../components/Players/the-boys/S1/PlayerThe Boys-S1E2";
import { PlayerTheBoysS2E1 } from "../components/Players/the-boys/S2/PlayerThe Boys-S2E1";
import { PlayerTheBoysS2E2 } from "../components/Players/the-boys/S2/PlayerThe Boys-S2E2";
import { PlayerTheBoysS2E3 } from "../components/Players/the-boys/S2/PlayerThe Boys-S2E3";
import { PlayerTheBoysS2E4 } from "../components/Players/the-boys/S2/PlayerThe Boys-S2E4";
import { PlayerTheBoysS2E5 } from "../components/Players/the-boys/S2/PlayerThe Boys-S2E5";
import { PlayerTheBoysS2E6 } from "../components/Players/the-boys/S2/PlayerThe Boys-S2E6";
import { PlayerTheBoysS2E7 } from "../components/Players/the-boys/S2/PlayerThe Boys-S2E7";
import { PlayerTheBoysS2E8 } from "../components/Players/the-boys/S2/PlayerThe Boys-S2E8";
import { PlayerTheBoysS3E1 } from "../components/Players/the-boys/S3/PlayerThe Boys-S3E1";
import { PlayerTheBoysS3E2 } from "../components/Players/the-boys/S3/PlayerThe Boys-S3E2";
import { PlayerTheBoysS3E3 } from "../components/Players/the-boys/S3/PlayerThe Boys-S3E3";
import { PlayerTheBoysS3E4 } from "../components/Players/the-boys/S3/PlayerThe Boys-S3E4";
import { PlayerTheBoysS3E5 } from "../components/Players/the-boys/S3/PlayerThe Boys-S3E5";
import { PlayerTheBoysS3E6 } from "../components/Players/the-boys/S3/PlayerThe Boys-S3E6";
import { PlayerTheBoysS3E7 } from "../components/Players/the-boys/S3/PlayerThe Boys-S3E7";
import { PlayerTheBoysS3E8 } from "../components/Players/the-boys/S3/PlayerThe Boys-S3E8";
import { PlayerStrangerThingsHome } from "../components/Players/stranger-things/S1/PlayerStrangerThings-Home";
import { PlayerStrangerThingsS1E1 } from "../components/Players/stranger-things/S1/PlayerStrangerThings-S1E1";
import { PlayerStrangerThingsS1E2 } from "../components/Players/stranger-things/S1/PlayerStrangerThings-S1E2";
import { PlayerStrangerThingsS1E3 } from "../components/Players/stranger-things/S1/PlayerStrangerThings-S1E3";
import { PlayerStrangerThingsS1E4 } from "../components/Players/stranger-things/S1/PlayerStrangerThings-S1E4";
import { PlayerStrangerThingsS1E5 } from "../components/Players/stranger-things/S1/PlayerStrangerThings-S1E5";
import { PlayerStrangerThingsS1E7 } from "../components/Players/stranger-things/S1/PlayerStrangerThings-S1E7";
import { PlayerStrangerThingsS1E6 } from "../components/Players/stranger-things/S1/PlayerStrangerThings-S1E6";
import { PlayerStrangerThingsS1E8 } from "../components/Players/stranger-things/S1/PlayerStrangerThings-S1E8";
import { PlayerBetterCallSaulHome } from "../components/Players/better caul soul/S1/PlayerBetterCaulSoul-Home";
import { PlayerBetterCallSaulS1E1 } from "../components/Players/better caul soul/S1/PlayerBetterCaulSoul-S1E1";
import { PlayerBetterCallSaulS1E2 } from "../components/Players/better caul soul/S1/PlayerBetterCaulSoul-S1E2";
import { PlayerBetterCallSaulS1E3 } from "../components/Players/better caul soul/S1/PlayerBetterCaulSoul-S1E3";
import { PlayerBetterCallSaulS1E4 } from "../components/Players/better caul soul/S1/PlayerBetterCaulSoul-S1E4";
import { PlayerBetterCallSaulS1E5 } from "../components/Players/better caul soul/S1/PlayerBetterCaulSoul-S1E5";
import { PlayerBetterCallSaulS1E6 } from "../components/Players/better caul soul/S1/PlayerBetterCaulSoul-S1E6";
import { PlayerBetterCallSaulS1E7 } from "../components/Players/better caul soul/S1/PlayerBetterCaulSoul-S1E7";
import { PlayerBetterCallSaulS1E8 } from "../components/Players/better caul soul/S1/PlayerBetterCaulSoul-S1E8";
import { PlayerBetterCallSaulS1E9 } from "../components/Players/better caul soul/S1/PlayerBetterCaulSoul-S1E9";
import { PlayerBetterCallSaulS1E10 } from "../components/Players/better caul soul/S1/PlayerBetterCaulSoul-S1E10";

export function SeriesPlayer() {
    const { slug } = useParams<{ slug: string }>()

    return (
        <div className="bg-gray-500 flex flex-col min-h-screen">
            <Header/>
            <main className="flex-1">
                {!slug ? <div className="flex-1"></div>
                    : slug === "got" ? <PlayerGotHome />
                        : slug === "got-S1E1" ? <PlayerGotS1E1 />
                            : slug === "got-S1E2" ? <PlayerGotS1E2 />
                                : slug === "got-S1E3" ? <PlayerGotS1E3 />
                                    : slug === "got-S1E4" ? <PlayerGotS1E4 />
                                        : slug === "got-S1E5" ? <PlayerGotS1E5 />
                                            : slug === "got-S1E6" ? <PlayerGotS1E6 />
                                                : slug === "got-S1E7" ? <PlayerGotS1E7 />
                                                    : slug === "got-S1E8" ? <PlayerGotS1E8 />
                                                        : slug === "got-S1E9" ? <PlayerGotS1E9 />
                                                            : slug === "got-S1E10" ? <PlayerGotS1E10 />
                                                                : slug === "got-S2E1" ? <PlayerGotS2E1 />
                                                                    : slug === "got-S2E2" ? <PlayerGotS2E2 />
                                                                        : slug === "got-S2E3" ? <PlayerGotS2E3 />
                                                                            : slug === "got-S2E4" ? <PlayerGotS2E4 />
                                                                                : slug === "got-S2E5" ? <PlayerGotS2E5 />
                                                                                    : slug === "got-S2E6" ? <PlayerGotS2E6 />
                                                                                        : slug === "got-S2E7" ? <PlayerGotS2E7 />
                                                                                            : slug === "got-S2E8" ? <PlayerGotS2E8 />
                                                                                                : slug === "got-S2E9" ? <PlayerGotS2E9 />
                                                                                                    : slug === "got-S2E10" ? <PlayerGotS2E10 />
                                                                                                        : slug === "got-S3E1" ? <PlayerGotS3E1 />
                                                                                                            : slug === "got-S3E2" ? <PlayerGotS3E2 />
                                                                                                                : slug === "got-S3E3" ? <PlayerGotS3E3 />
                                                                                                                    : slug === "got-S3E4" ? <PlayerGotS3E4 />
                                                                                                                        : slug === "got-S3E5" ? <PlayerGotS3E5 />
                                                                                                                            : slug === "got-S3E6" ? <PlayerGotS3E6 />
                                                                                                                                : slug === "got-S3E7" ? <PlayerGotS3E7 />
                                                                                                                                    : slug === "got-S3E8" ? <PlayerGotS3E8 />
                                                                                                                                        : slug === "got-S3E9" ? <PlayerGotS3E9 />
                                                                                                                                            : slug === "got-S3E10" ? <PlayerGotS3E10 />
                                                                                                                                                : slug === "got-S4E1" ? <PlayerGotS4E1 />
                                                                                                                                                    : slug === "got-S4E2" ? <PlayerGotS4E2 />
                                                                                                                                                        : slug === "got-S4E3" ? <PlayerGotS4E3 />
                                                                                                                                                            : slug === "got-S4E4" ? <PlayerGotS4E4 />
                                                                                                                                                                : slug === "got-S4E5" ? <PlayerGotS4E5 />
                                                                                                                                                                    : slug === "got-S4E6" ? <PlayerGotS4E6 />
                                                                                                                                                                        : slug === "got-S4E7" ? <PlayerGotS4E7 />
                                                                                                                                                                            : slug === "got-S4E8" ? <PlayerGotS4E8 />
                                                                                                                                                                                : slug === "got-S4E9" ? <PlayerGotS4E9 />
                                                                                                                                                                                    : slug === "got-S4E10" ? <PlayerGotS4E10 />
                                                                                                                                                                                        : slug === "got-S5E1" ? <PlayerGotS5E1 />
                                                                                                                                                                                            : slug === "got-S5E2" ? <PlayerGotS5E2 />
                                                                                                                                                                                                : slug === "got-S5E3" ? <PlayerGotS5E3 />
                                                                                                                                                                                                    : slug === "got-S5E4" ? <PlayerGotS5E4 />
                                                                                                                                                                                                        : slug === "got-S5E5" ? <PlayerGotS5E5 />
                                                                                                                                                                                                            : slug === "got-S5E6" ? <PlayerGotS5E6 />
                                                                                                                                                                                                                : slug === "got-S5E7" ? <PlayerGotS5E7 />
                                                                                                                                                                                                                    : slug === "got-S5E8" ? <PlayerGotS5E8 />
                                                                                                                                                                                                                        : slug === "got-S5E9" ? <PlayerGotS5E9 />
                                                                                                                                                                                                                            : slug === "got-S5E10" ? <PlayerGotS5E10 />
                                                                                                                                                                                                                                : slug === "breaking-bad" ? <PlayerBreakingBadHome />
                                                                                                                                                                                                                                    : slug === "breaking-bad-S1E1" ? <PlayerBreakingBadS1E1 />
                                                                                                                                                                                                                                        : slug === "breaking-bad-S1E2" ? <PlayerBreakingBadS1E2 />
                                                                                                                                                                                                                                            : slug === "breaking-bad-S1E3" ? <PlayerBreakingBadS1E3 />
                                                                                                                                                                                                                                                : slug === "breaking-bad-S1E4" ? <PlayerBreakingBadS1E4 />
                                                                                                                                                                                                                                                    : slug === "breaking-bad-S1E5" ? <PlayerBreakingBadS1E5 />
                                                                                                                                                                                                                                                        : slug === "breaking-bad-S1E6" ? <PlayerBreakingBadS1E6 />
                                                                                                                                                                                                                                                            : slug === "breaking-bad-S1E7" ? <PlayerBreakingBadS1E7 />
                                                                                                                                                                                                                                                                : slug === "breaking-bad-S2E1" ? <PlayerBreakingBadS2E1 />
                                                                                                                                                                                                                                                                    : slug === "breaking-bad-S2E2" ? <PlayerBreakingBadS2E2 />
                                                                                                                                                                                                                                                                        : slug === "breaking-bad-S2E3" ? <PlayerBreakingBadS2E3 />
                                                                                                                                                                                                                                                                            : slug === "breaking-bad-S2E4" ? <PlayerBreakingBadS2E4 />
                                                                                                                                                                                                                                                                                : slug === "breaking-bad-S2E5" ? <PlayerBreakingBadS2E5 />
                                                                                                                                                                                                                                                                                    : slug === "breaking-bad-S2E6" ? <PlayerBreakingBadS2E6 />
                                                                                                                                                                                                                                                                                        : slug === "breaking-bad-S2E7" ? <PlayerBreakingBadS2E7 />
                                                                                                                                                                                                                                                                                            : slug === "breaking-bad-S2E8" ? <PlayerBreakingBadS2E8 />
                                                                                                                                                                                                                                                                                                : slug === "breaking-bad-S2E9" ? <PlayerBreakingBadS2E9 />
                                                                                                                                                                                                                                                                                                    : slug === "breaking-bad-S2E10" ? <PlayerBreakingBadS2E10 />
                                                                                                                                                                                                                                                                                                        : slug === "breaking-bad-S3E1" ? <PlayerBreakingBadS3E1 />
                                                                                                                                                                                                                                                                                                            : slug === "breaking-bad-S3E2" ? <PlayerBreakingBadS3E2 />
                                                                                                                                                                                                                                                                                                                : slug === "breaking-bad-S3E3" ? <PlayerBreakingBadS3E3 />
                                                                                                                                                                                                                                                                                                                    : slug === "breaking-bad-S3E4" ? <PlayerBreakingBadS3E4 />
                                                                                                                                                                                                                                                                                                                        : slug === "breaking-bad-S3E5" ? <PlayerBreakingBadS3E5 />
                                                                                                                                                                                                                                                                                                                            : slug === "breaking-bad-S3E6" ? <PlayerBreakingBadS3E6 />
                                                                                                                                                                                                                                                                                                                                : slug === "breaking-bad-S3E7" ? <PlayerBreakingBadS3E7 />
                                                                                                                                                                                                                                                                                                                                    : slug === "breaking-bad-S3E8" ? <PlayerBreakingBadS3E8 />
                                                                                                                                                                                                                                                                                                                                        : slug === "breaking-bad-S3E9" ? <PlayerBreakingBadS3E9 />
                                                                                                                                                                                                                                                                                                                                            : slug === "breaking-bad-S3E10" ? <PlayerBreakingBadS3E10 />
                                                                                                                                                                                                                                                                                                                                                : slug === "breaking-bad-S4E1" ? <PlayerBreakingBadS4E1 />
                                                                                                                                                                                                                                                                                                                                                    : slug === "breaking-bad-S4E2" ? <PlayerBreakingBadS4E2 />
                                                                                                                                                                                                                                                                                                                                                        : slug === "breaking-bad-S4E3" ? <PlayerBreakingBadS4E3 />
                                                                                                                                                                                                                                                                                                                                                            : slug === "breaking-bad-S4E4" ? <PlayerBreakingBadS4E4 />
                                                                                                                                                                                                                                                                                                                                                                : slug === "breaking-bad-S4E5" ? <PlayerBreakingBadS4E5 />
                                                                                                                                                                                                                                                                                                                                                                    : slug === "breaking-bad-S4E6" ? <PlayerBreakingBadS4E6 />
                                                                                                                                                                                                                                                                                                                                                                        : slug === "breaking-bad-S4E7" ? <PlayerBreakingBadS4E7 />
                                                                                                                                                                                                                                                                                                                                                                            : slug === "breaking-bad-S4E8" ? <PlayerBreakingBadS4E8 />
                                                                                                                                                                                                                                                                                                                                                                                : slug === "breaking-bad-S4E9" ? <PlayerBreakingBadS4E9 />
                                                                                                                                                                                                                                                                                                                                                                                    : slug === "breaking-bad-S4E10" ? <PlayerBreakingBadS4E10 />
                                                                                                                                                                                                                                                                                                                                                                                        : slug === "breaking-bad-S5E1" ? <PlayerBreakingBadS5E1 />
                                                                                                                                                                                                                                                                                                                                                                                            : slug === "breaking-bad-S5E2" ? <PlayerBreakingBadS5E2 />
                                                                                                                                                                                                                                                                                                                                                                                                : slug === "breaking-bad-S5E3" ? <PlayerBreakingBadS5E3 />
                                                                                                                                                                                                                                                                                                                                                                                                    : slug === "breaking-bad-S5E4" ? <PlayerBreakingBadS5E4 />
                                                                                                                                                                                                                                                                                                                                                                                                        : slug === "breaking-bad-S5E5" ? <PlayerBreakingBadS5E5 />
                                                                                                                                                                                                                                                                                                                                                                                                            : slug === "breaking-bad-S5E6" ? <PlayerBreakingBadS5E6 />
                                                                                                                                                                                                                                                                                                                                                                                                                : slug === "breaking-bad-S5E7" ? <PlayerBreakingBadS5E7 />
                                                                                                                                                                                                                                                                                                                                                                                                                    : slug === "breaking-bad-S5E8" ? <PlayerBreakingBadS5E8 />
                                                                                                                                                                                                                                                                                                                                                                                                                        : slug === "the-boys" ? <PlayerTheBoysHome />
                                                                                                                                                                                                                                                                                                                                                                                                                            : slug === "the-boys-S1E1" ? <PlayerTheBoysS1E1 />
                                                                                                                                                                                                                                                                                                                                                                                                                                : slug === "the-boys-S1E2" ? <PlayerTheBoysS1E2 />
                                                                                                                                                                                                                                                                                                                                                                                                                                    : slug === "the-boys-S1E3" ? <PlayerTheBoysS1E3 />
                                                                                                                                                                                                                                                                                                                                                                                                                                        : slug === "the-boys-S1E4" ? <PlayerTheBoysS1E4 />
                                                                                                                                                                                                                                                                                                                                                                                                                                            : slug === "the-boys-S1E5" ? <PlayerTheBoysS1E5 />
                                                                                                                                                                                                                                                                                                                                                                                                                                                : slug === "the-boys-S1E6" ? <PlayerTheBoysS1E6 />
                                                                                                                                                                                                                                                                                                                                                                                                                                                    : slug === "the-boys-S1E7" ? <PlayerTheBoysS1E7 />
                                                                                                                                                                                                                                                                                                                                                                                                                                                        : slug === "the-boys-S1E8" ? <PlayerTheBoysS1E8 />
                                                                                                                                                                                                                                                                                                                                                                                                                                                            : slug === "the-boys-S2E1" ? <PlayerTheBoysS2E1 />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                : slug === "the-boys-S2E2" ? <PlayerTheBoysS2E2 />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    : slug === "the-boys-S2E3" ? <PlayerTheBoysS2E3 />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        : slug === "the-boys-S2E4" ? <PlayerTheBoysS2E4 />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            : slug === "the-boys-S2E5" ? <PlayerTheBoysS2E5 />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                : slug === "the-boys-S2E6" ? <PlayerTheBoysS2E6 />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    : slug === "the-boys-S2E7" ? <PlayerTheBoysS2E7 />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        : slug === "the-boys-S2E8" ? <PlayerTheBoysS2E8 />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            : slug === "the-boys-S3E1" ? <PlayerTheBoysS3E1 />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                : slug === "the-boys-S3E2" ? <PlayerTheBoysS3E2 />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    : slug === "the-boys-S3E3" ? <PlayerTheBoysS3E3 />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        : slug === "the-boys-S3E4" ? <PlayerTheBoysS3E4 />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            : slug === "the-boys-S3E5" ? <PlayerTheBoysS3E5 />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                : slug === "the-boys-S3E6" ? <PlayerTheBoysS3E6 />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    : slug === "the-boys-S3E7" ? <PlayerTheBoysS3E7 />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        : slug === "the-boys-S3E8" ? <PlayerTheBoysS3E8 />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            : slug === "stranger-things" ? <PlayerStrangerThingsHome />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                : slug === "stranger-things-S1E1" ? <PlayerStrangerThingsS1E1 />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    : slug === "stranger-things-S1E2" ? <PlayerStrangerThingsS1E2 />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        : slug === "stranger-things-S1E3" ? <PlayerStrangerThingsS1E3 />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            : slug === "stranger-things-S1E4" ? <PlayerStrangerThingsS1E4 />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                : slug === "stranger-things-S1E5" ? <PlayerStrangerThingsS1E5 />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    : slug === "stranger-things-S1E6" ? <PlayerStrangerThingsS1E6 />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        : slug === "stranger-things-S1E7" ? <PlayerStrangerThingsS1E7 />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            : slug === "stranger-things-S1E8" ? <PlayerStrangerThingsS1E8 />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                : slug === "better-call-soul" ? <PlayerBetterCallSaulHome />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    : slug === "better-call-saul-S1E1" ? <PlayerBetterCallSaulS1E1 />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        : slug === "better-call-saul-S1E2" ? <PlayerBetterCallSaulS1E2 />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            : slug === "better-call-saul-S1E3" ? <PlayerBetterCallSaulS1E3 />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                : slug === "better-call-saul-S1E4" ? <PlayerBetterCallSaulS1E4 />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    : slug === "better-call-saul-S1E5" ? <PlayerBetterCallSaulS1E5 />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        : slug === "better-call-saul-S1E6" ? <PlayerBetterCallSaulS1E6 />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            : slug === "better-call-saul-S1E7" ? <PlayerBetterCallSaulS1E7 />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                : slug === "better-call-saul-S1E8" ? <PlayerBetterCallSaulS1E8 />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    : slug === "better-call-saul-S1E9" ? <PlayerBetterCallSaulS1E9 />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        : slug === "better-call-saul-S1E10" ? <PlayerBetterCallSaulS1E10 />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            : ''
                }
            </main>
        </div>
    )
}
